# Generated by Django 2.0.13 on 2019-11-16 10:09

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191114_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='content',
            field=wagtail.core.fields.StreamField([('inline_image', wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.CharBlock(help_text='Add image description.', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('paragraph', streams.blocks.SimpleRichTextBlock())], null=True),
        ),
    ]
