# Generated by Django 2.2.7 on 2019-11-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_authorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorProfile',
        ),
    ]
