# Generated by Django 2.0.13 on 2019-11-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteowner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorprofile',
            options={'verbose_name': 'Site Owner', 'verbose_name_plural': 'Site Owners'},
        ),
    ]
